baseURL = 'https://backtobasics.github.io/'
languageCode = 'fr'
title = 'BackToBasics'

defaultContentLanguage = 'fr'


[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[params]
    [params.docs]
        darkMode = true
        titleIcon = false
        descriptions = true
        author = true
        #themeColor = "blue" #blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
    [params.blog]
        showImage = true
    [params.flexsearch]
        enabled = true

[markup]
   [markup.goldmark.renderer]
        unsafe = true # allow html in md files
    
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'catppuccin-mocha'
        tabWidth = 4

[[menu.primary]]
    name  = "Annonces"
    url = "/blog/"
    identifier = "blog"
    weight = 10

[params.social]
    discord = "PtXWatnH4j"
    twitch = "backtobasicsepita"
