baseURL = 'https://backtobasics.github.io/'
languageCode = 'en-us'
title = 'BackToBasics'

[module]
    # uncomment line below for temporary local development of module,
    # when using a 'theme' as a git submodule or git cloned files
    replacements = "github.com/colinwilson/lotusdocs -> lotusdocs"
    [[module.imports]]
        path = "github.com/colinwilson/lotusdocs"
        disable = false
    [[module.imports]]
        path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
        disable = false

[markup.goldmark.renderer]
  unsafe = true # allow html in md files

[params]
    [params.docs]
        darkMode = true
        titleIcon = true
        descriptions = true
        author = true
        #themeColor = "blue" #blue (default), green, red, yellow, emerald, cardinal, magenta, cyan
    [params.blog]
        showImage = true
    [params.flexsearch]
        enabled = true

[markup]
    [markup.goldmark.renderer]
        unsafe = true
    
    [markup.highlight]
        anchorLineNos = false
        codeFences = true
        guessSyntax = false
        hl_inline = false
        lineAnchors = ''
        lineNoStart = 1
        lineNos = false
        lineNumbersInTable = true
        noClasses = true
        noHl = false
        style = 'catppuccin-mocha'
        tabWidth = 4